### ISSUE TITLE
Support pre-lollipop devices

### ISSUE THREAD

**Issue by KOLANICH** [MBach/AutoAirplaneMode#10]

**Comment by MBach** [comment]
I'm using WakefulBroadcastReceiver but it's now deprecated. The solution provided by Google is to use Job Scheduler API. I can lower the minSDK to API level 21, but I won't go below.

**Comment by ontologiae** [comment]
Pretty interesting, because I want to make it work on Android 5.1.1...
So if I lower the sdk to API level 21 it will compile ?
I'm probably going to try....
