### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by ghost** [MBach/AutoAirplaneMode#11]

**Comment by MBach** [comment]
Hello @waqasanwar94. You can post your design here. I'll can take a look directly, like everyone else.

**Comment by waqasanwar94** [comment]
ok @MBach  i will send you soon

**Comment by waqasanwar94** [comment]
![untitled-1 copy](https://user-images.githubusercontent.com/38813945/40169665-f1a2f6e2-59df-11e8-934d-9e0b42ed5c6b.png)

Hello sir please have a look and let know if you like any logo from these i can change more if you want to change any thing
