### ISSUE TITLE
Not work on android 8.1

### ISSUE THREAD

**Issue by Flavien06** [MBach/AutoAirplaneMode#12]
Hi,
The app does not work on android 8.1
(I use Nexus 4 with LineageOS 15.1 with microg, root Magisk)

**Comment by MBach** [comment]
Hello @Flavien06 
Actually, I don't own any more a rootable phone, so it's kind of complicated to fix this one. Any help will be greatly appreciated.

**Comment by Flavien06** [comment]
Sorry, It is my phone the problem.
I deleted the root authorisation in magisk, restarted by clearing the cache and it works fine.
