### ISSUE TITLE
Force close on android 8

### ISSUE THREAD

**Issue by ThmsP** [MBach/AutoAirplaneMode#9]
Hello, I recently updated my device on a aosp rom based on Android 8.0 and I noticed that the app force close shortly after its opening. 
I can help to the debugging.

**Comment by MBach** [comment]
Hi,
Unfortunately, I now have a locked bootloader (US Galaxy S7) and I can't have root access any more. I can still merge pull request but this project is kind of "on hold".

**Comment by ThmsP** [comment]
Hi, 
I made a fresh install of the rom and in the process I made a complete installation of root and AutoAirplaneMode is now fully fonctionnal, no more force close. 
So just a missing root problem, sorry for the bug opening.
